/*
    Copyright (C) 2026, The AROS Development Team. All rights reserved.

    Desc: Bounded D1001 GSL3670 reset and RAM-firmware transport.
*/

/*
 * This file contains no touch-controller firmware.  C4 diagnostic builds may
 * name a private header generated by tools/convert-gsl-firmware.py.  That
 * header stays outside the source tree and supplies only the record array.
 * A normal build neither includes nor executes this code path.
 *
 * The controller loses its program when it loses power.  Every transaction is
 * therefore checked and the first failure stops the load.  No retry loop can
 * hide a broken bus or hold the boot forever: krnP4I2CTransfer() itself has a
 * 50-ms deadline, and this layer attempts every record at most once.
 */

#include <inttypes.h>
#include <aros/touchscreen.h>
#include <exec/types.h>

#include "hardware.h"
#include "kernel_intern.h"

#if defined(P4_C4_TOUCH_LOAD) || defined(P4_C4_TOUCH_HIDD)

#ifdef P4_C4_TOUCH_LOAD
#ifndef P4_GSL_FW_HEADER
#error P4_C4_TOUCH_LOAD requires a private P4_GSL_FW_HEADER
#endif

struct P4GSLFirmwareRecord
{
    unsigned char offset;
    unsigned long value;
};

#include P4_GSL_FW_HEADER
#endif

#define GSL_RESET_WAIT_TICKS   2U  /* 20 ms with the 100-Hz kernel timer */
#define GSL_SHORT_WAIT_TICKS   1U  /* bounded 10 ms; timer granularity */
#define GSL_STATUS_WAIT_TICKS  3U  /* 30 ms */

static int gsl_expander_read16(unsigned char reg, UWORD *value)
{
    unsigned char data[2] = { 0, 0 };
    int r = krnP4I2CTransfer(P4_PCA9535_ADDR, &reg, 1, data, 2);

    if (r == P4_I2C_OK)
        *value = (UWORD)(data[0] | ((UWORD)data[1] << 8));
    return r;
}

static int gsl_expander_write16(unsigned char reg, UWORD value)
{
    unsigned char data[3];

    data[0] = reg;
    data[1] = (unsigned char)value;
    data[2] = (unsigned char)(value >> 8);
    return krnP4I2CTransfer(P4_PCA9535_ADDR, data, 3, NULL, 0);
}

static int gsl_expander_write_checked(unsigned char reg, UWORD value)
{
    UWORD readback = 0;
    int r = gsl_expander_write16(reg, value);

    if (r != P4_I2C_OK)
        return r;
    r = gsl_expander_read16(reg, &readback);
    if (r != P4_I2C_OK)
        return r;
    return readback == value ? P4_I2C_OK : P4_I2C_MISMATCH;
}

/*
 * Pulse only PCA9535 output 12, preserving every unrelated latch and
 * direction bit.  The low value is installed in the latch before an inherited
 * input is changed to an output, so claiming the pin cannot produce a high
 * glitch.  It remains a driven high output afterwards because that is the
 * controller's released-reset operating state.
 */
static int gsl_hardware_reset(void)
{
    UWORD output = 0, config = 0;
    int r;

    if (!krnP4I2CInit(1, P4_BOARD_I2C1_SDA_GPIO,
                      P4_BOARD_I2C1_SCL_GPIO, 100000UL))
        return P4_I2C_NOTREADY;

    r = gsl_expander_read16(P4_PCA9535_OUTPUT, &output);
    if (r != P4_I2C_OK)
        return r;
    r = gsl_expander_read16(P4_PCA9535_CONFIG, &config);
    if (r != P4_I2C_OK)
        return r;

    r = gsl_expander_write_checked(P4_PCA9535_OUTPUT,
                                   (UWORD)(output & ~P4_EXP_TOUCH_RST));
    if (r != P4_I2C_OK)
        return r;
    r = gsl_expander_write_checked(P4_PCA9535_CONFIG,
                                   (UWORD)(config & ~P4_EXP_TOUCH_RST));
    if (r != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_RESET_WAIT_TICKS);

    r = gsl_expander_write_checked(P4_PCA9535_OUTPUT,
                                   (UWORD)(output | P4_EXP_TOUCH_RST));
    if (r != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_RESET_WAIT_TICKS);
    return P4_I2C_OK;
}

static int gsl_select_bus(void)
{
    return krnP4I2CInit(0, P4_BOARD_I2C0_SDA_GPIO,
                        P4_BOARD_I2C0_SCL_GPIO, 10000UL)
         ? P4_I2C_OK : P4_I2C_NOTREADY;
}

static int gsl_write(unsigned char reg, unsigned long value,
                     unsigned int bytes)
{
    unsigned char data[5];
    unsigned int i;

    data[0] = reg;
    for (i = 0; i < bytes; ++i)
        data[i + 1] = (unsigned char)(value >> (i * 8));
    return krnP4I2CTransfer(P4_BOARD_TOUCH_ADDR, data, bytes + 1, NULL, 0);
}

static int gsl_read32(unsigned char reg, uint32_t *value)
{
    unsigned char data[4] = { 0, 0, 0, 0 };
    int r = krnP4I2CTransfer(P4_BOARD_TOUCH_ADDR, &reg, 1, data, 4);

    if (r == P4_I2C_OK)
        *value = (uint32_t)data[0] | ((uint32_t)data[1] << 8)
               | ((uint32_t)data[2] << 16) | ((uint32_t)data[3] << 24);
    return r;
}

static int gsl_clear_registers(void)
{
    int r = gsl_hardware_reset();

    if (r != P4_I2C_OK)
        return r;
    if ((r = gsl_select_bus()) != P4_I2C_OK)
        return r;
    if ((r = gsl_write(0x88, 0x01, 1)) != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_SHORT_WAIT_TICKS);
    if ((r = gsl_write(0xE4, 0x04, 1)) != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_SHORT_WAIT_TICKS);
    if ((r = gsl_write(0xE0, 0x00, 1)) != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_RESET_WAIT_TICKS);
    return P4_I2C_OK;
}

static int gsl_reset_registers(void)
{
    int r = gsl_hardware_reset();

    if (r != P4_I2C_OK)
        return r;
    if ((r = gsl_select_bus()) != P4_I2C_OK)
        return r;
    if ((r = gsl_write(0xE4, 0x04, 1)) != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_SHORT_WAIT_TICKS);
    if ((r = gsl_write(0xBC, 0x00000000UL, 4)) != P4_I2C_OK)
        return r;
    krnTimerWait(GSL_SHORT_WAIT_TICKS);
    return P4_I2C_OK;
}

#ifdef P4_C4_TOUCH_LOAD
static int gsl_load_embedded_firmware(unsigned int *failed_record)
{
    unsigned int i;

    for (i = 0; i < P4_GSL_FW_RECORD_COUNT; ++i)
    {
        const struct P4GSLFirmwareRecord *record = &p4_gsl_firmware[i];
        int r = gsl_write(record->offset, record->value,
                          record->offset == 0xF0 ? 1 : 4);

        if (r != P4_I2C_OK)
        {
            *failed_record = i;
            return r;
        }
        if ((i & 0x3FFU) == 0x3FFU)
        {
            krnP4PutStr("[touch]  firmware records sent ");
            krnP4PutDec(i + 1);
            krnP4PutStr("/");
            krnP4PutDec(P4_GSL_FW_RECORD_COUNT);
            krnP4PutStr("\n");
        }
    }
    return P4_I2C_OK;
}
#endif

static int gsl_start(void)
{
    int r = gsl_write(0xE0, 0x00, 1);

    if (r == P4_I2C_OK)
        krnTimerWait(GSL_SHORT_WAIT_TICKS);
    return r;
}

/*
 * Diagnostic-only complete bootstrap.  Success means only that the volatile
 * program is alive and that one bounded status read matches; input reporting
 * and HIDD integration are deliberately later gates.
 */
#ifdef P4_C4_TOUCH_LOAD
int krnP4GSLLoadDiagnostic(uint32_t *status, unsigned int *failed_record)
{
    int r;

    *status = 0;
    *failed_record = 0;

    krnP4PutStr("[touch]  private firmware records ");
    krnP4PutDec(P4_GSL_FW_RECORD_COUNT);
    krnP4PutStr(", sha256 " P4_GSL_FW_SHA256 "\n");

    if ((r = gsl_clear_registers()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_reset_registers()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_load_embedded_firmware(failed_record)) != P4_I2C_OK)
        goto out;
    if ((r = gsl_start()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_reset_registers()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_start()) != P4_I2C_OK)
        goto out;
    krnTimerWait(GSL_STATUS_WAIT_TICKS);
    r = gsl_read32(0xB0, status);
    if (r == P4_I2C_OK && *status != 0x5A5A5A5AUL)
        r = P4_I2C_MISMATCH;

out:
    /* The normal C3 display path owns the singleton transport after C4. */
    if (!krnP4I2CInit(1, P4_BOARD_I2C1_SDA_GPIO,
                      P4_BOARD_I2C1_SCL_GPIO, 100000UL)
        && r == P4_I2C_OK)
        r = P4_I2C_NOTREADY;
    return r;
}
#endif

#ifdef P4_C4_TOUCH_HIDD
#define GSL_REPORT_REGISTER  0x80U
#define GSL_REPORT_BYTES     44U
#define GSL_CONTACT_OFFSET   4U
#define GSL_CONTACT_BYTES    4U

static ULONG gsl_get_le32(const UBYTE *p)
{
    return (ULONG)p[0] | ((ULONG)p[1] << 8) | ((ULONG)p[2] << 16)
         | ((ULONG)p[3] << 24);
}

/*
 * Runtime firmware transport.  The HIDD owns filesystem access; the kernel
 * owns all controller-specific validation and I2C/reset sequencing.  Every
 * record is checked before the first transaction, so a malformed external
 * file cannot partially reprogram the controller.  The exact record count is
 * deliberately D1001-specific and rejects similarly named Silead images.
 */
static LONG gsl_touch_load_firmware(const UBYTE *data, ULONG bytes,
                                    ULONG *failed_record, ULONG *status)
{
    ULONG i, pages = 0;
    int r = P4_I2C_OK;

    if (failed_record)
        *failed_record = 0;
    if (status)
        *status = 0;
    if (!data || !failed_record || !status
        || bytes != KRN_TOUCHSCREEN_FW_BYTES)
        return P4_I2C_TOOLONG;

    for (i = 0; i < KRN_TOUCHSCREEN_FW_RECORDS; ++i)
    {
        ULONG offset = gsl_get_le32(data + i * 8U);
        ULONG value = gsl_get_le32(data + i * 8U + 4U);

        if (offset == 0xF0U)
        {
            if (value > 0xFFU)
            {
                *failed_record = i;
                return P4_I2C_MISMATCH;
            }
            ++pages;
        }
        else if (offset > 0x7CU || (offset & 3U))
        {
            *failed_record = i;
            return P4_I2C_MISMATCH;
        }
    }
    if (!pages)
        return P4_I2C_MISMATCH;

    if ((r = gsl_clear_registers()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_reset_registers()) != P4_I2C_OK)
        goto out;
    for (i = 0; i < KRN_TOUCHSCREEN_FW_RECORDS; ++i)
    {
        ULONG offset = gsl_get_le32(data + i * 8U);
        ULONG value = gsl_get_le32(data + i * 8U + 4U);

        r = gsl_write((UBYTE)offset, value, offset == 0xF0U ? 1U : 4U);
        if (r != P4_I2C_OK)
        {
            *failed_record = i;
            goto out;
        }
    }
    if ((r = gsl_start()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_reset_registers()) != P4_I2C_OK)
        goto out;
    if ((r = gsl_start()) != P4_I2C_OK)
        goto out;
    krnTimerWait(GSL_STATUS_WAIT_TICKS);
    r = gsl_read32(0xB0, status);
    if (r == P4_I2C_OK && *status != 0x5A5A5A5AUL)
        r = P4_I2C_MISMATCH;

out:
    /* Leave the shared controller on the board-management bus.  acquire()
       selects I2C0 only after a complete successful load. */
    if (!krnP4I2CInit(1, P4_BOARD_I2C1_SDA_GPIO,
                      P4_BOARD_I2C1_SCL_GPIO, 100000UL)
        && r == P4_I2C_OK)
        r = P4_I2C_NOTREADY;
    return r;
}

/*
 * Reserve the singleton transport for the worker's bounded polling session.
 * The hardware-verified raw sampler selects I2C0 once and keeps it selected;
 * resetting the host controller and changing buses for every report is not
 * equivalent and suppresses live reports on the D1001.  No other runtime
 * consumer exists yet.  The worker returns ownership to I2C1 on every exit.
 */
static BOOL gsl_touch_acquire(void)
{
    return gsl_select_bus() == P4_I2C_OK;
}

static VOID gsl_touch_release(void)
{
    krnP4I2CInit(1, P4_BOARD_I2C1_SDA_GPIO,
                 P4_BOARD_I2C1_SCL_GPIO, 100000UL);
}

/*
 * Read and decode one coherent task-context report for the public platform
 * contract.  The wire format is kept here rather than leaking into the HIDD:
 * byte zero is the controller count and each four-byte record contains 12-bit
 * Y, 12-bit X and a four-bit hardware ID.  A non-zero high nibble alongside Y
 * marks controller auxiliary data, not a screen contact, and is omitted.
 *
 * The 44-byte transaction is deliberately one I2C transaction.  The P4
 * transport drains its 30-byte FIFO at an END boundary without issuing STOP,
 * so the second part cannot come from a later touch frame.
 */
static BOOL gsl_read_contacts(struct KrnTouchScreenFrame *frame)
{
    unsigned char reg = GSL_REPORT_REGISTER;
    unsigned char data[GSL_REPORT_BYTES];
    ULONG reported, bounded, i;
    int r;

    if (!frame)
        return FALSE;
    frame->reported_count = 0;
    frame->count = 0;
    for (i = 0; i < KRN_TOUCHSCREEN_MAX_CONTACTS; ++i)
    {
        frame->contact[i].id = 0;
        frame->contact[i].x = 0;
        frame->contact[i].y = 0;
    }

    r = krnP4I2CTransfer(P4_BOARD_TOUCH_ADDR, &reg, 1,
                         data, GSL_REPORT_BYTES);
    if (r != P4_I2C_OK)
        return FALSE;

    reported = data[0];
    bounded = reported > KRN_TOUCHSCREEN_MAX_CONTACTS
            ? KRN_TOUCHSCREEN_MAX_CONTACTS : reported;
    frame->reported_count = reported;
    for (i = 0; i < bounded; ++i)
    {
        ULONG offset = GSL_CONTACT_OFFSET + i * GSL_CONTACT_BYTES;
        ULONG auxiliary = (ULONG)data[offset + 1] >> 4;
        struct KrnTouchScreenContact *contact;

        if (auxiliary)
            continue;
        contact = &frame->contact[frame->count++];
        contact->y = (ULONG)data[offset]
                   | (((ULONG)data[offset + 1] & 0x0FU) << 8);
        contact->x = (ULONG)data[offset + 2]
                   | (((ULONG)data[offset + 3] & 0x0FU) << 8);
        contact->id = (ULONG)data[offset + 3] >> 4;
    }
    return TRUE;
}

/* The vendor configuration names 26 driver and 14 sensor lines at 64 raw
   units each, and a 1280x800 output domain. */
static struct KrnTouchScreenOps gsl_touchscreen_ops =
{
    KRN_TOUCHSCREEN_OPS_VERSION,
    26U * 64U,
    14U * 64U,
    1280,
    800,
    gsl_touch_load_firmware,
    gsl_touch_acquire,
    gsl_touch_release,
    gsl_read_contacts
};

struct KrnTouchScreenOps *krnP4GSLTouchScreenOps(void)
{
    return &gsl_touchscreen_ops;
}
#endif /* P4_C4_TOUCH_HIDD */

#ifdef P4_C4_TOUCH_SAMPLE
/*
 * Read only contact zero.  Eight bytes cover the count at byte zero and the
 * first four-byte contact at bytes four through seven.  This older bounded
 * diagnostic remains intentionally distinct from the maintained HIDD's full
 * coherent-frame path.
 */
int krnP4GSLSampleDiagnostic(unsigned int seconds)
{
    unsigned char reg = 0x80;
    unsigned char data[8];
    unsigned int polls = 0, touches = 0, releases = 0, changes = 0;
    unsigned int printed = 0, last_count = ~0U, last_x = ~0U, last_y = ~0U;
    unsigned int last_id = ~0U, saw_touch = 0;
    unsigned int min_x = ~0U, min_y = ~0U, max_x = 0, max_y = 0;
    unsigned int limit = seconds * 20U;
    int r = P4_I2C_OK;

    if (limit / 20U != seconds)
        return P4_I2C_TOOLONG;
    if ((r = gsl_select_bus()) != P4_I2C_OK)
        goto out;

    krnP4PutStr("[touch]  raw contact-zero sampling for ");
    krnP4PutDec(seconds);
    krnP4PutStr(" seconds; touch and move now\n");

    while (polls < limit)
    {
        unsigned int count, x = 0, y = 0, id = 0;

        r = krnP4I2CTransfer(P4_BOARD_TOUCH_ADDR, &reg, 1, data, 8);
        if (r != P4_I2C_OK)
            break;
        ++polls;

        count = data[0];
        if (count)
        {
            y = (unsigned int)data[4] | ((unsigned int)data[5] << 8);
            x = (unsigned int)data[6]
              | (((unsigned int)data[7] & 0x0FU) << 8);
            id = (unsigned int)data[7] >> 4;
            ++touches;
            saw_touch = 1;
            if (x < min_x) min_x = x;
            if (x > max_x) max_x = x;
            if (y < min_y) min_y = y;
            if (y > max_y) max_y = y;
        }
        else if (last_count != ~0U && last_count != 0)
            ++releases;

        if (count != last_count || (count &&
            (x != last_x || y != last_y || id != last_id)))
        {
            ++changes;
            if (printed < 80U)
            {
                krnP4PutStr("[touch]  raw count ");
                krnP4PutDec(count);
                if (count)
                {
                    krnP4PutStr(" id ");
                    krnP4PutDec(id);
                    krnP4PutStr(" x ");
                    krnP4PutDec(x);
                    krnP4PutStr(" y ");
                    krnP4PutDec(y);
                }
                krnP4PutStr(" irq ");
                krnP4PutDec((p4_r32(P4_GPIO_BASE + P4_GPIO_IN)
                             >> P4_BOARD_TOUCH_IRQ_GPIO) & 1U);
                krnP4PutStr("\n");
                ++printed;
            }
        }
        last_count = count;
        last_x = x;
        last_y = y;
        last_id = id;
        krnTimerWait(P4_TICK_HZ / 20U);
    }

    krnP4PutStr("[touch]  raw summary polls ");
    krnP4PutDec(polls);
    krnP4PutStr(" touches ");
    krnP4PutDec(touches);
    krnP4PutStr(" releases ");
    krnP4PutDec(releases);
    krnP4PutStr(" changes ");
    krnP4PutDec(changes);
    if (saw_touch)
    {
        krnP4PutStr(" x ");
        krnP4PutDec(min_x);
        krnP4PutStr("..");
        krnP4PutDec(max_x);
        krnP4PutStr(" y ");
        krnP4PutDec(min_y);
        krnP4PutStr("..");
        krnP4PutDec(max_y);
    }
    if (changes > printed)
    {
        krnP4PutStr(" printed-first ");
        krnP4PutDec(printed);
    }
    krnP4PutStr("\n");

out:
    if (!krnP4I2CInit(1, P4_BOARD_I2C1_SDA_GPIO,
                      P4_BOARD_I2C1_SCL_GPIO, 100000UL)
        && r == P4_I2C_OK)
        r = P4_I2C_NOTREADY;
    return r;
}
#endif /* P4_C4_TOUCH_SAMPLE */

#endif /* P4_C4_TOUCH_LOAD || P4_C4_TOUCH_HIDD */
