##begin config
basename        I2CDW
libbasetype     struct I2CDWBase
version         0.1
superclass      CLID_Hidd_I2C
classptr_field  i2c_DrvClass
residentpri     75
##end config
##begin cdef
#include <exec/types.h>
##end cdef
##begin cdefprivate
#include <hidd/i2c.h>
#include "i2c_dw.h"
##end cdefprivate
##begin methodlist
.interface Hidd_I2C
PutByte
GetByte
WriteRead
##end methodlist
