##begin config
basename        RamTest
version         1.0
libbasetype     struct RamTestBase
libbase         RamTestBase
residentpri     3
beginio_func    BeginIO
abortio_func    AbortIO
options         noexpunge
##end config

##begin cdefprivate
#include "ramtest_device.h"
##end cdefprivate

##begin cdef
#include <exec/devices.h>
#include <exec/io.h>
##end cdef
