##begin config
basename        Touch
libbase         TouchBase
libbasetype     struct TouchBase
version         1.0
residentpri     10
classid         CLID_Hidd_Mouse_TouchScreen
superclass      CLID_Hidd_Mouse
classptr_field  tsd.touchClass
classdatatype   struct TouchData
oopbase_field   tsd.cs_OOPBase
sysbase_field   tsd.cs_SysBase
seglist_field   tsd.cs_SegList
options         noexpunge
##end config

##begin cdefprivate
#include "touchscreen_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
Set
##end methodlist
