##begin config
basename        P4Touch
libbase         P4TouchBase
libbasetype     struct P4TouchBase
version         1.0
residentpri     8
classid         CLID_Hidd_Mouse_P4Touch
superclass      CLID_Hidd_Mouse
classptr_field  ptd.mouseclass
classdatatype   struct P4TouchMouseData
oopbase_field   ptd.cs_OOPBase
sysbase_field   ptd.cs_SysBase
seglist_field   ptd.cs_SegList
##end config

##begin cdefprivate
#include "p4touch_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
##end methodlist
