##begin config
basename        FlashDisk
version         1.0
libbasetype     struct FlashDiskBase
libbase         FlashDiskBase
residentpri     5
beginio_func    BeginIO
abortio_func    AbortIO
options         noexpunge
##end config

##begin cdef
#include <exec/devices.h>
#include <exec/io.h>

struct FlashDiskBase
{
    struct Device   fd_Device;
};
##end cdef
