##begin config
basename        P4I2C
libbase         P4I2CBase
libbasetype     struct P4I2CBase
version         1.0
residentpri     88
oopbase_field   psd.OOPBase
classid         CLID_Hidd_I2C_ESP32P4
superclass      CLID_Hidd_I2C
classptr_field  psd.busClass
classdatatype   struct p4i2c_busdata
options noexpunge
##end config

##begin cdef
#include <exec/types.h>
##end cdef

##begin cdefprivate
#include <hidd/i2c.h>
#include "p4i2c_intern.h"
##end cdefprivate

##begin methodlist
.interface Root
New
Dispose
Get
.interface Hidd_I2C
Start
Address
Stop
PutByte
GetByte
WriteRead
ProbeAddress
##end methodlist
