##begin config
basename        P4Board
version         1.0
libbase         P4BoardBase
libbasetype     struct P4BoardBase
sysbase_field   pb_SysBase
residentpri     8
options         noincludes, noexpunge, noautolib, selfinit
##end config

##begin cdefprivate
#include "esp32p4board_intern.h"
##end cdefprivate
