##begin config
basename C2Screen
version 1.0
libbase C2ScreenBase
libbasetype struct C2ScreenBase
sysbase_field c2s_SysBase
residentpri 8
options noincludes, noexpunge, noautolib, selfinit
##end config

##begin cdefprivate
#include "c2screen_intern.h"
##end cdefprivate
